### PR TITLE
start constraint animation with keyboard animation

### PR DESCRIPTION
**Pull request by torstenlehmann**
If I use `keyboardAdjusterAnimated = true` then this version animates nicely up and down with the keyboard.

### CODE REVIEW

**Review by dlo — CHANGES_REQUESTED** [review]
@torstenlehmann Apologies for the late review here—did you have a chance to test this to make sure it works across multiple devices and interface orientations? Also, if you could, please pull in the latest updates from master so that the tests can run :)

**Comment by torstenlehmann** [comment]
Can't see why tests are failing now. Running `xcodebuild test -scheme TestApplication -target TestApplication -destination "platform=iOS Simulator,name=iPhone SE,OS=10.1" -destination-timeout 1 ONLY_ACTIVE_ARCH=NO` locally succeeds on my system.

**Review by dlo — APPROVED** [review]

**Comment by dlo** [comment]
Weird. I'll blame Travis.

**Comment by dlo** [comment]
Thanks!

**Pull request merged**
